# Generated by Django 5.0.14 on 2025-09-25 14:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_alter_move_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tournament name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Tournament description')),
                ('format', models.CharField(choices=[('SWISS', 'Swiss System'), ('SINGLE_ELIMINATION', 'Single Elimination'), ('ROUND_ROBIN', 'Round Robin')], default='SWISS', max_length=20)),
                ('status', models.CharField(choices=[('REGISTRATION', 'Registration Open'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='REGISTRATION', max_length=20)),
                ('max_participants', models.IntegerField(default=16, help_text='Maximum number of participants', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(256)])),
                ('join_code', models.CharField(help_text='Unique code for joining tournament', max_length=20, unique=True)),
                ('is_public', models.BooleanField(default=True, help_text='Public tournaments appear in listings')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Deadline for registration', null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text='Tournament start time', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Tournament end time', null=True)),
                ('current_round', models.IntegerField(default=0, help_text='Current round number')),
                ('total_rounds', models.IntegerField(blank=True, help_text='Total planned rounds (calculated for some formats)', null=True)),
                ('time_control', models.JSONField(default=dict, help_text='Time control settings (minutes, increment, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Tournament organizer', on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seed', models.IntegerField(blank=True, help_text='Player seeding (1 = highest seed)', null=True)),
                ('initial_rating', models.IntegerField(help_text="Player's rating when joining tournament")),
                ('score', models.FloatField(default=0.0, help_text='Tournament points (1 for win, 0.5 for draw, 0 for loss)')),
                ('tiebreak_scores', models.JSONField(default=dict, help_text='Tiebreaker scores (Buchholz, Sonneborn-Berger, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='False if player withdrew from tournament')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament Participant',
                'verbose_name_plural': 'Tournament Participants',
                'ordering': ['-score', 'seed'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(help_text='Round number (1-based)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Round',
                'verbose_name_plural': 'Tournament Rounds',
                'ordering': ['tournament', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPairing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, choices=[('WHITE_WIN', 'White Wins'), ('BLACK_WIN', 'Black Wins'), ('DRAW', 'Draw'), ('BYE', 'Bye'), ('FORFEIT_WHITE', 'White Forfeits'), ('FORFEIT_BLACK', 'Black Forfeits')], max_length=20, null=True)),
                ('board_number', models.IntegerField(blank=True, help_text='Physical board number for camera assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_black_pairings', to=settings.AUTH_USER_MODEL)),
                ('bye_player', models.ForeignKey(blank=True, help_text='Player receiving bye (odd number of participants)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_bye_pairings', to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(blank=True, help_text='Associated game (if not a bye)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_pairing', to='game.game')),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_white_pairings', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='tournaments.tournamentround')),
            ],
            options={
                'verbose_name': 'Tournament Pairing',
                'verbose_name_plural': 'Tournament Pairings',
                'ordering': ['round', 'board_number'],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'is_public'], name='tournaments_status_e75501_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['join_code'], name='tournaments_join_co_fc8666_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['created_by'], name='tournaments_created_ffc179_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', 'is_active'], name='tournaments_tournam_028da0_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', 'score'], name='tournaments_tournam_c5fe2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'user')},
        ),
        migrations.AddIndex(
            model_name='tournamentround',
            index=models.Index(fields=['tournament', 'round_number'], name='tournaments_tournam_454197_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentround',
            index=models.Index(fields=['status'], name='tournaments_status_57828b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentround',
            unique_together={('tournament', 'round_number')},
        ),
        migrations.AddIndex(
            model_name='tournamentpairing',
            index=models.Index(fields=['round'], name='tournaments_round_i_71169f_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentpairing',
            index=models.Index(fields=['white_player'], name='tournaments_white_p_5f4562_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentpairing',
            index=models.Index(fields=['black_player'], name='tournaments_black_p_06e646_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentpairing',
            index=models.Index(fields=['game'], name='tournaments_game_id_bcbb20_idx'),
        ),
    ]
