# XADRAS - Vision AI Integration Fields Migration
# Generated by Tournament Logic AI - 2025-09-25T18:12:05+01:00
# CRITICAL: Create migration BEFORE using fields in code

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpairing',
            name='physical_board_id',
            field=models.CharField(
                max_length=10, 
                null=True, 
                blank=True,
                help_text="Physical board identifier for Vision AI (e.g., 'A1', 'B2')"
            ),
        ),
        migrations.AddField(
            model_name='tournamentpairing',
            name='camera_id',
            field=models.IntegerField(
                null=True, 
                blank=True,
                help_text="Camera ID for Vision AI integration"
            ),
        ),
    ]
