# Generated by Django 5.0.14 on 2026-03-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_add_vision_integration_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='format',
            new_name='tournament_type',
        ),
        migrations.AddField(
            model_name='tournament',
            name='increment',
            field=models.IntegerField(default=0, help_text='Increment added per move (seconds)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='vision_enabled',
            field=models.BooleanField(default=False, help_text='Enable physical board tracking integration'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='time_control',
            field=models.CharField(default='10+0', help_text='Time control string (e.g. 10+0)', max_length=50),
        ),
    ]
