services:
  backend:
    build:
      context: ./backend
      target: dev
    working_dir: /usr/src/app/xadras
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
      - "5173:5173"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=xadras.settings_dev
    depends_on:
      - db
      - redis
    networks:
      - xadras-network

  frontend:
    build:
      context: ./frontend
      target: dev
    network_mode: service:backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --config vite.config.dev.ts --host
