# Generated by Django 5.0.14 on 2025-09-25 14:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_alter_move_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Camera display name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Camera description')),
                ('camera_type', models.CharField(choices=[('USB', 'USB Camera'), ('IP', 'IP Camera'), ('RTSP', 'RTSP Camera'), ('HTTP', 'HTTP Camera')], max_length=10)),
                ('connection_url', models.URLField(help_text='Camera connection URL (e.g., rtsp://user:pass@192.168.1.100:554/stream)', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Camera IP address', null=True)),
                ('port', models.IntegerField(blank=True, help_text='Camera port number', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.CharField(blank=True, help_text='Camera authentication username', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Camera authentication password', max_length=100)),
                ('location', models.CharField(help_text="Physical location description (e.g., 'Board 1', 'Table A')", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Camera is active and available for use')),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ERROR', 'Error'), ('CALIBRATING', 'Calibrating'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=20)),
                ('last_health_check', models.DateTimeField(blank=True, help_text='Last successful health check', null=True)),
                ('calibration_data', models.JSONField(default=dict, help_text='Camera calibration data from Vision AI')),
                ('is_calibrated', models.BooleanField(default=False, help_text='Camera has been calibrated by Vision AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who registered this camera', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CameraHealthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ERROR', 'Error'), ('CALIBRATING', 'Calibrating'), ('MAINTENANCE', 'Maintenance')], help_text='Camera status at time of check', max_length=20)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('error_message', models.TextField(blank=True, help_text='Error message if health check failed')),
                ('checked_at', models.DateTimeField(auto_now_add=True, help_text='When health check was performed')),
                ('camera', models.ForeignKey(help_text='Camera that was checked', on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Camera Health Log',
                'verbose_name_plural': 'Camera Health Logs',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, help_text='Stream is currently active')),
                ('started_at', models.DateTimeField(blank=True, help_text='When stream was started', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When stream was ended', null=True)),
                ('quality_settings', models.JSONField(default=dict, help_text='Stream quality settings (resolution, fps, etc.)')),
                ('recording_enabled', models.BooleanField(default=False, help_text='Enable recording of this stream')),
                ('recording_path', models.CharField(blank=True, help_text='Path to recorded file (if recording enabled)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(help_text='Camera providing the stream', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='cameras.camera')),
                ('game', models.ForeignKey(help_text='Game being streamed', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='game.game')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['status', 'is_active'], name='cameras_cam_status_e6302e_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['location'], name='cameras_cam_locatio_9424f0_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['camera_type'], name='cameras_cam_camera__1ab111_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['created_by'], name='cameras_cam_created_0c1b02_idx'),
        ),
        migrations.AddIndex(
            model_name='camerahealthlog',
            index=models.Index(fields=['camera', '-checked_at'], name='cameras_cam_camera__ebbcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='camerahealthlog',
            index=models.Index(fields=['status'], name='cameras_cam_status_ad440e_idx'),
        ),
        migrations.AddIndex(
            model_name='camerahealthlog',
            index=models.Index(fields=['-checked_at'], name='cameras_cam_checked_e4ea4d_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['camera', 'is_active'], name='cameras_str_camera__1f3bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['game'], name='cameras_str_game_id_175e55_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['is_active'], name='cameras_str_is_acti_0f695f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('camera',), name='unique_active_stream_per_camera'),
        ),
    ]
