# Generated by Django 5.0.14 on 2026-04-12 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1000)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preferred_color', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('ANY', 'Any')], default='ANY', max_length=5)),
                ('time_control', models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical'), ('unlimited', 'Sem Tempo')], default='rapid', max_length=20)),
                ('is_guest', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matchmaking Queue',
                'verbose_name_plural': 'Matchmaking Queue',
                'ordering': ['joined_at'],
            },
        ),
    ]
