# Generated by Django 5.2.3 on 2025-06-13 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_queue_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_color', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('ANY', 'Any')], default='ANY', max_length=5)),
                ('is_guest', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matchmaking Queue',
                'verbose_name_plural': 'Matchmaking Queue',
            },
        ),
    ]
