# Generated by Django 5.2.4 on 2025-07-09 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_add_rating_and_joined_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchmakingqueue',
            options={'ordering': ['joined_at'], 'verbose_name': 'Matchmaking Queue', 'verbose_name_plural': 'Matchmaking Queue'},
        ),
        migrations.RemoveField(
            model_name='matchmakingqueue',
            name='entered_queue_at',
        ),
        migrations.AlterField(
            model_name='matchmakingqueue',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
