# Generated by Django 5.0.14 on 2026-03-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_alter_matchmakingqueue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmakingqueue',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
    ]
