# Generated by Django 5.0.14 on 2026-04-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_alter_matchmakingqueue_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakingqueue',
            name='time_control',
            field=models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical'), ('unlimited', 'Sem Tempo')], default='rapid', max_length=20),
        ),
    ]
