# Generated by Django 5.0.14 on 2025-07-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='move',
            unique_together={('game', 'move_number')},
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['game', 'move_number'], name='game_move_game_id_9838e8_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['game', 'created_at'], name='game_move_game_id_c26b34_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['created_at'], name='game_move_created_be71b2_idx'),
        ),
    ]
