# Generated by Django 5.0.14 on 2026-04-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_time_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('LIVE_CAPTURE', 'Live Capture')], default='ONLINE', max_length=20),
        ),
    ]
